name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [1.x, "1.8.2", canary, ~1.7]

    name: Run on Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - run: |
          deno --version
          ./scripts/format.sh
          ./scripts/lint.sh
          ./scripts/compile.sh
