name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: ["v1.7.0", "nightly"]
    name: Run on Deno ${{ matrix.deno }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: |
          deno --version
          ./scripts/format.sh
          ./scripts/lint.sh
          ./scripts/compile.sh
